---
title: "Gov 50 Final Project"
author: "Lillian Cooper"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---


## Project thoughts

I am interested in exploring data related to... how abortions and miscarriages are related in California 

## Paragraph thing...


```{r}
library(tidyverse)
library(readr)
head(NationalAndStatePregnancy_PublicUse)

abortion_and_mis <- NationalAndStatePregnancy_PublicUse |>
  select(state, year, abortionratelt20: abortionrate40plus, miscarriageslt20: miscarriages40plus)
head(abortion_and_births)


CA_abortion_and_mis <- abortion_and_mis |>
  subset(state == "CA")
CA_abortion_and_mis
```
## Abortion Plot

```{r}
library(dplyr)
library(broom)


CAabort_plot <- CA_abortion_and_mis |> 
  ggplot(mapping = aes(y = abortionrate2024)) + geom_point(mapping = aes(x = year))

```

## Miscarriage Plot

```{r}
CAmis_plot <- CA_abortion_and_mis |>
  ggplot(mapping = aes(y = miscarriages2024)) + geom_point(mapping = aes(x = year))

```

## Together plot

```{r}
CAtogether_plot <- CA_abortion_and_mis |>
  ggplot(mapping = aes(y = miscarriages2024)) + geom_point(mapping = aes(x = abortionrate2024))
CAtogether_plot

```

## Linear regression lol

```{r}
lm(miscarriages2024 ~ abortionrate2024, data = CA_abortion_and_mis)

```

## How many pregnancies overall in California overtime? (may not be very useful)

```{r}
CA_pregnancies <- NationalAndStatePregnancy_PublicUse |>
  select(state, year, pregnancyrate2024) |>
  subset(state == "CA")
head(CA_pregnancies)

CA_pregnancies |> 
  ggplot(mapping = aes(x = year)) + geom_point(mapping = aes(y = pregnancyrate2024))
  


```
